<?php
/**
 * {{THEME_NAME}} functions and definitions.
 *
 * Generated by Child Theme Maker. Add your own code below the loader.
 *
 * @package {{THEME_SLUG}}
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/*
 * Loads the parent theme stylesheet and this child's style.css, unless the
 * parent theme already does it.
 */
add_action(
	'wp_enqueue_scripts',
	static function () {
		$styles     = wp_styles();
		$parent_uri = get_template_directory_uri() . '/style.css';
		$child_uri  = get_stylesheet_directory_uri() . '/style.css';
		$parent     = '';
		$child      = '';

		foreach ( $styles->registered as $handle => $style ) {
			if ( ! is_string( $style->src ) || '' === $style->src ) {
				continue;
			}
			$src = strtok( set_url_scheme( $style->src ), '?' );
			if ( '' === $parent && set_url_scheme( $parent_uri ) === $src ) {
				$parent = $handle;
			} elseif ( '' === $child && set_url_scheme( $child_uri ) === $src ) {
				$child = $handle;
			}
		}

		if ( '' === $parent ) {
			$parent = 'ctmaker-parent-style';
			wp_enqueue_style( $parent, $parent_uri, array(), wp_get_theme( get_template() )->get( 'Version' ) );
		}

		if ( '' === $child ) {
			wp_enqueue_style( 'ctmaker-child-style', $child_uri, array( $parent ), wp_get_theme()->get( 'Version' ) );
		} else {
			// The parent registered the child's sheet as its main one; load the parent's first.
			if ( ! in_array( $parent, $styles->registered[ $child ]->deps, true ) ) {
				$styles->registered[ $child ]->deps[] = $parent;
			}
			wp_enqueue_style( $child );
		}
	},
	20
);
